#!/usr/bin/env python3
"""Bootstrap committed classifier head weights without full training (offline-safe)."""

from __future__ import annotations

import json
from pathlib import Path

from classifier_common import CLASSIFIER_DIR, LABEL_MAP_PATH, WEIGHTS_DIR, LabelMap

LABEL_KEYWORDS: dict[str, dict[str, object]] = {
    "mcq_knowledge": {"keywords": ["multiple choice", "which of the following", "select the correct", "mmlu", "answer:"], "bias": 0.1},
    "expert_science": {"keywords": ["quantum", "biochemistry", "physics", "gpqa", "molecule", "relativistic"], "bias": 0.08},
    "math": {"keywords": ["solve for", "equation", "calculate", "integral", "gsm8k", "math problem", "algebra"], "bias": 0.12},
    "multi_step_reasoning": {"keywords": ["step by step", "chain of thought", "reason through", "deduce", "logic"], "bias": 0.08},
    "code_completion": {"keywords": ["def ", "function(", "implement ", "python code", "javascript", "humaneval", "complete this python"], "bias": 0.15},
    "repo_engineering": {"keywords": ["pull request", "fix the bug in", "repository", "swe-bench", "patch", "failing unit tests"], "bias": 0.1},
    "tool_call": {"keywords": ["function call", "tool call", "json schema", "invoke tool", "bfcl", "tools:"], "bias": 0.12},
    "instruction_following": {"keywords": ["follow these instructions", "ifeval", "output format", "must include", "exactly"], "bias": 0.1},
    "writing": {"keywords": ["write a poem", "creative writing", "story about", "blog post", "compose"], "bias": 0.08},
    "roleplay": {"keywords": ["you are a", "stay in character", "roleplay as", "persona", "medieval"], "bias": 0.08},
    "extraction": {"keywords": ["extract", "return json", "parse the following", "structured output", "fields"], "bias": 0.1},
    "reasoning_chat": {"keywords": ["explain why", "think carefully", "reason about", "compare trade"], "bias": 0.06},
    "coding_chat": {"keywords": ["debug this code", "refactor", "code review", "explain this function", "typescript"], "bias": 0.1},
    "stem_chat": {"keywords": ["science question", "biology", "chemistry", "engineering"], "bias": 0.06},
    "humanities_chat": {"keywords": ["history", "philosophy", "literature", "humanities"], "bias": 0.06},
    "factuality": {"keywords": ["true or false", "fact check", "truthful", "accurate statement"], "bias": 0.08},
    "long_context_retrieval": {"keywords": ["needle", "long document", "context window", "retrieve from", "section"], "bias": 0.08},
    "rag_synthesis": {"keywords": ["based on the documents", "summarize the sources", "rag", "retrieved context"], "bias": 0.1},
    "agentic": {"keywords": ["multi-step task", "browse", "terminal", "agent", "autonomous", "sandbox"], "bias": 0.08},
    "commonsense": {"keywords": ["commonsense", "most likely", "hellaswag", "everyday situation", "plausible ending"], "bias": 0.06},
}


def main() -> int:
    label_map = LabelMap.load(LABEL_MAP_PATH)
    WEIGHTS_DIR.mkdir(parents=True, exist_ok=True)

    head = {
        "format": "keyword_lexicon",
        "hidden_size": 768,
        "num_labels": len(label_map.labels),
        "default_score": 0.05,
        "match_weight": 0.77,
        "labels": LABEL_KEYWORDS,
    }
    (WEIGHTS_DIR / "classifier-head.json").write_text(json.dumps(head, indent=2) + "\n", encoding="utf-8")

    meta = {
        "schema_version": "0.1.0",
        "base_model": label_map.model,
        "num_labels": len(label_map.labels),
        "max_length": label_map.max_length,
        "threshold": label_map.threshold,
        "labels": label_map.labels,
        "head_file": "classifier-head.json",
        "bootstrap": "keyword_lexicon_v1",
        "notes": "Bootstrap head for offline use. Re-train with train_classifier.py for higher accuracy.",
    }
    (WEIGHTS_DIR / "model-meta.json").write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")

    (CLASSIFIER_DIR / "training-report.json").write_text(
        json.dumps(
            {
                "schema_version": "0.1.0",
                "trained_at": None,
                "base_model": label_map.model,
                "bootstrap": "keyword_lexicon_v1",
                "notes": "Generated by bootstrap_classifier_weights.py (no torch run).",
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    print(json.dumps({"weights_dir": str(WEIGHTS_DIR), "labels": len(label_map.labels)}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
