import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const WEIGHTS_DIR = path.join(ROOT, 'classifier', 'weights');
const LABEL_MAP_PATH = path.join(ROOT, 'classifier', 'label_map.json');

const LABEL_KEYWORDS: Record<string, { keywords: string[]; bias: number }> = {
  mcq_knowledge: { keywords: ['multiple choice', 'which of the following', 'select the correct', 'mmlu', 'answer:'], bias: 0.1 },
  expert_science: { keywords: ['quantum', 'biochemistry', 'physics', 'gpqa', 'molecule', 'relativistic'], bias: 0.08 },
  math: { keywords: ['solve for', 'equation', 'calculate', 'integral', 'gsm8k', 'math problem', 'algebra'], bias: 0.12 },
  multi_step_reasoning: { keywords: ['step by step', 'chain of thought', 'reason through', 'deduce', 'logic'], bias: 0.08 },
  code_completion: { keywords: ['def ', 'function(', 'implement ', 'python code', 'javascript', 'humaneval', 'complete this python'], bias: 0.15 },
  repo_engineering: { keywords: ['pull request', 'fix the bug in', 'repository', 'swe-bench', 'patch', 'failing unit tests'], bias: 0.1 },
  tool_call: { keywords: ['function call', 'tool call', 'json schema', 'invoke tool', 'bfcl', 'tools:'], bias: 0.12 },
  instruction_following: { keywords: ['follow these instructions', 'ifeval', 'output format', 'must include', 'exactly'], bias: 0.1 },
  writing: { keywords: ['write a poem', 'creative writing', 'story about', 'blog post', 'compose'], bias: 0.08 },
  roleplay: { keywords: ['you are a', 'stay in character', 'roleplay as', 'persona', 'medieval'], bias: 0.08 },
  extraction: { keywords: ['extract', 'return json', 'parse the following', 'structured output', 'fields'], bias: 0.1 },
  reasoning_chat: { keywords: ['explain why', 'think carefully', 'reason about', 'compare trade'], bias: 0.06 },
  coding_chat: { keywords: ['debug this code', 'refactor', 'code review', 'explain this function', 'typescript'], bias: 0.1 },
  stem_chat: { keywords: ['science question', 'biology', 'chemistry', 'engineering'], bias: 0.06 },
  humanities_chat: { keywords: ['history', 'philosophy', 'literature', 'humanities'], bias: 0.06 },
  factuality: { keywords: ['true or false', 'fact check', 'truthful', 'accurate statement'], bias: 0.08 },
  long_context_retrieval: { keywords: ['needle', 'long document', 'context window', 'retrieve from', 'section'], bias: 0.08 },
  rag_synthesis: { keywords: ['based on the documents', 'summarize the sources', 'rag', 'retrieved context'], bias: 0.1 },
  agentic: { keywords: ['multi-step task', 'browse', 'terminal', 'agent', 'autonomous', 'sandbox'], bias: 0.08 },
  commonsense: { keywords: ['commonsense', 'most likely', 'hellaswag', 'everyday situation', 'plausible ending'], bias: 0.06 },
};

function main(): void {
  const labelMap = JSON.parse(fs.readFileSync(LABEL_MAP_PATH, 'utf-8')) as {
    model: string;
    max_length: number;
    threshold: number;
    labels: string[];
  };

  const head = {
    format: 'keyword_lexicon',
    hidden_size: 768,
    num_labels: labelMap.labels.length,
    default_score: 0.05,
    match_weight: 0.77,
    labels: LABEL_KEYWORDS,
  };

  fs.mkdirSync(WEIGHTS_DIR, { recursive: true });
  fs.writeFileSync(path.join(WEIGHTS_DIR, 'classifier-head.json'), `${JSON.stringify(head, null, 2)}\n`);
  fs.writeFileSync(
    path.join(WEIGHTS_DIR, 'model-meta.json'),
    `${JSON.stringify(
      {
        schema_version: '0.1.0',
        base_model: labelMap.model,
        num_labels: labelMap.labels.length,
        max_length: labelMap.max_length,
        threshold: labelMap.threshold,
        labels: labelMap.labels,
        head_file: 'classifier-head.json',
        bootstrap: 'keyword_lexicon_v1',
        notes:
          'Bootstrap head for offline use. Re-train with train_classifier.py for higher-accuracy DistilBERT head weights.',
      },
      null,
      2,
    )}\n`,
  );
  fs.writeFileSync(
    path.join(ROOT, 'classifier', 'training-report.json'),
    `${JSON.stringify(
      {
        schema_version: '0.1.0',
        trained_at: null,
        base_model: labelMap.model,
        bootstrap: 'keyword_lexicon_v1',
        notes: 'Generated by bootstrap-classifier-weights.ts (no torch run).',
      },
      null,
      2,
    )}\n`,
  );

  console.log(JSON.stringify({ weights_dir: WEIGHTS_DIR, labels: labelMap.labels.length }, null, 2));
}

main();
